version: '3.8'

services:
  spacetask-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEBUG=False
      - SECRET_KEY=production-secret-key-change-this
      - JWT_SECRET=production-jwt-secret-change-this
      - DATABASE_PATH=/app/data/spacetask.db
      - UPLOAD_FOLDER=/app/uploads
      - BASE_URL=http://localhost:8000
    volumes:
      # Persist database and uploads
      - spacetask_data:/app/data
      - spacetask_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  spacetask_data:
    driver: local
  spacetask_uploads:
    driver: local 