version: '3.8'

services:
  spacetask-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - JWT_SECRET=${JWT_SECRET:-change-this-jwt-secret}
      - DATABASE_PATH=/app/data/spacetask.db
      - UPLOAD_FOLDER=/app/uploads
      - BASE_URL=${BASE_URL:-http://silverflag.net:8000}
      - MAX_FILE_SIZE=5242880
    volumes:
      # Persist database and uploads
      - spacetask_data:/app/data
      - spacetask_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spacetask-backend
    restart: unless-stopped
    profiles:
      - with-nginx

volumes:
  spacetask_data:
    driver: local
  spacetask_uploads:
    driver: local 